/* =========================================================================
 * books.js —— 书单推荐预置数据（纯前端，无后端 / 无数据库）
 * -------------------------------------------------------------------------
 * 数据全部写死在本文件里，作为「今日书单推荐」功能的预置书库。
 * 字段说明：
 *   title           书名
 *   author          作者
 *   cover           封面图直链（由 _gen_covers.js 抓取的真实豆瓣封面；留空 '' 时渲染占位封面）
 *   summary         一句话简介（50 字以内）
 *   rating          豆瓣评分（数值）
 *   category        分类（与 bookRecommend.js 的分类标签保持一致）
 *   doubanUrl       豆瓣链接（真实可打开：用豆瓣搜索页，输入书名即出结果）
 *   wereadSearchUrl 微信读书搜索链接（真实可打开）
 *
 * 链接策略（保证“打不开的假链接”问题彻底解决）：
 *   - doubanUrl 统一用 https://www.douban.com/search?q=书名
 *     这是豆瓣官方的搜索页，输入书名后会直接列出该书，100% 可打开。
 *   - wereadSearchUrl 用 https://weread.qq.com/web/search/books?keyword=书名
 *     这是微信读书官方的网页搜索，可打开并搜到该书。
 * 如需改成具体的 subject 详情页（如 https://book.douban.com/subject/xxxx/），
 * 只需把对应书的 doubanUrl 换成真实 subject 链接即可，逻辑无需改动。
 * ========================================================================= */

(function () {
  'use strict';

  // 豆瓣搜索链接（真实可打开）
  function doubanUrl(title) {
    return 'https://www.douban.com/search?q=' + encodeURIComponent(title);
  }
  // 微信读书网页搜索链接（真实可打开）
  function wereadSearchUrl(title) {
    return 'https://weread.qq.com/web/search/books?keyword=' + encodeURIComponent(title);
  }

  // 原始数据：每行 [书名, 作者, 分类, 评分, 一句话简介]
  // 分类取值：小说 / 历史 / 科技 / 哲学 / 心理学 / 经济 / 艺术 / 传记 / 散文 / 社会科学
  const RAW = [
    /* ===================== 小说（27 本） ===================== */
    ['百年孤独', '加西亚·马尔克斯', '小说', 9.3, '布恩迪亚家族七代人的魔幻传奇与孤独'],
    ['活着', '余华', '小说', 9.4, '福贵在苦难中坚韧活着的一生'],
    ['追风筝的人', '卡勒德·胡赛尼', '小说', 8.9, '阿富汗少年的背叛与救赎'],
    ['了不起的盖茨比', '菲茨杰拉德', '小说', 8.5, '爵士时代美国梦的华丽与幻灭'],
    ['围城', '钱钟书', '小说', 9.0, '婚姻如围城，城外的人想进去'],
    ['平凡的世界', '路遥', '小说', 9.0, '孙少安兄弟在时代洪流中的奋斗'],
    ['三体', '刘慈欣', '小说', 9.4, '三体文明入侵地球的硬科幻史诗'],
    ['红楼梦', '曹雪芹', '小说', 9.6, '贾府兴衰与宝黛爱情悲剧'],
    ['1984', '乔治·奥威尔', '小说', 9.4, '极权社会下被监控的思想'],
    ['霍乱时期的爱情', '加西亚·马尔克斯', '小说', 9.0, '跨越半世纪的等待与爱'],
    ['飘', '玛格丽特·米切尔', '小说', 9.3, '乱世佳人斯嘉丽的倔强'],
    ['卡拉马佐夫兄弟', '陀思妥耶夫斯基', '小说', 9.5, '一桩弑父案中的信仰追问'],
    ['老人与海', '海明威', '小说', 8.5, '人与鲨鱼搏斗的硬汉赞歌'],
    ['麦田里的守望者', '塞林格', '小说', 8.1, '叛逆少年的迷茫与疏离'],
    ['挪威的森林', '村上春树', '小说', 8.0, '青春、死亡与爱的怅惘'],
    ['白夜行', '东野圭吾', '小说', 9.1, '雪穗与亮司共生的罪恶'],
    ['解忧杂货店', '东野圭吾', '小说', 8.5, '穿越时空的温情回信'],
    ['小王子', '圣埃克苏佩里', '小说', 9.0, '献给所有曾是孩子的大人'],
    ['悲惨世界', '雨果', '小说', 9.4, '冉阿让的救赎与人间苦难'],
    ['安娜·卡列尼娜', '托尔斯泰', '小说', 9.2, '婚外情与社会枷锁的悲剧'],
    ['骆驼祥子', '老舍', '小说', 8.6, '车夫祥子三起三落的沉沦'],
    ['边城', '沈从文', '小说', 8.7, '湘西渡口的纯美与怅惘'],
    ['战争与和平', '托尔斯泰', '小说', 9.3, '拿破仑战争下的俄国家族'],
    ['檀香刑', '莫言', '小说', 8.5, '清末酷刑与人性的荒诞'],
    ['长恨歌', '王安忆', '小说', 8.3, '上海小姐王琦瑶的半生浮华'],
    ['许三观卖血记', '余华', '小说', 8.9, '苦难里小人物用幽默撑住的日子'],
    ['兄弟', '余华', '小说', 8.0, '两兄弟在荒诞时代的命运'],

    /* ===================== 历史（22 本） ===================== */
    ['人类简史', '尤瓦尔·赫拉利', '历史', 9.1, '从动物到上帝的简明人类史'],
    ['万历十五年', '黄仁宇', '历史', 9.0, '平淡一年窥见大明衰败'],
    ['明朝那些事儿', '当年明月', '历史', 9.2, '白话讲透大明三百年'],
    ['史记', '司马迁', '历史', 9.5, '纪传体通史之祖'],
    ['资治通鉴', '司马光', '历史', 9.4, '帝王治乱兴衰的镜鉴'],
    ['枪炮、病菌与钢铁', '贾雷德·戴蒙德', '历史', 8.8, '人类社会命运的环境根源'],
    ['全球通史', '斯塔夫里阿诺斯', '历史', 9.0, '从史前到当下的世界史'],
    ['中国历代政治得失', '钱穆', '历史', 9.2, '汉唐宋明清制度简析'],
    ['罗马人的故事', '盐野七生', '历史', 8.7, '千年罗马兴衰全景'],
    ['大秦帝国', '孙皓晖', '历史', 8.8, '商鞅变法到一统天下'],
    ['中国大历史', '黄仁宇', '历史', 8.5, '宏观俯瞰华夏兴衰'],
    ['战争史', '修昔底德', '历史', 8.9, '伯罗奔尼撒战争实录'],
    ['叫魂', '孔飞力', '历史', 9.0, '乾隆朝妖术恐慌的政治逻辑'],
    ['第二次世界大战战史', '李德·哈特', '历史', 8.9, '全景式二战军事史'],
    ['大国的兴衰', '保罗·肯尼迪', '历史', 8.6, '五百年经济与军事变迁'],
    ['菊花与刀', '鲁思·本尼迪克特', '历史', 8.6, '日本文化中的耻感与菊刀'],
    ['旧制度与大革命', '托克维尔', '历史', 8.9, '法国大革命前的社会逻辑'],
    ['丝绸之路', '彼得·弗兰科潘', '历史', 8.4, '重新发现世界中心地带'],
    ['国史大纲', '钱穆', '历史', 9.3, '通览中国历代兴衰'],
    ['天朝的崩溃', '茅海建', '历史', 8.7, '鸦片战争的多维再审视'],
    ['罗马帝国衰亡史', '爱德华·吉本', '历史', 8.9, '千年帝国衰落的宏大叙事'],
    ['1453', '罗杰·克劳利', '历史', 8.6, '君士坦丁堡陷落之战'],

    /* ===================== 科技（22 本） ===================== */
    ['时间简史', '史蒂芬·霍金', '科技', 8.8, '从大爆炸到黑洞的宇宙图景'],
    ['自私的基因', '理查德·道金斯', '科技', 8.8, '基因视角下的进化与利他'],
    ['未来简史', '尤瓦尔·赫拉利', '科技', 8.4, '智人之后的人类命运'],
    ['上帝掷骰子吗：量子物理史话', '曹天元', '科技', 9.2, '量子物理通俗史话'],
    ['从一到无穷大', '伽莫夫', '科技', 9.1, '科普经典的趣味数学物理'],
    ['浪潮之巅', '吴军', '科技', 9.0, 'IT 企业兴衰与科技浪潮'],
    ['人月神话', '弗雷德里克·布鲁克斯', '科技', 8.6, '软件工程管理的经典'],
    ['代码大全', '史蒂夫·麦康奈尔', '科技', 9.0, '软件开发实践全集'],
    ['失控', '凯文·凯利', '科技', 8.7, '万物演化与去中心化系统'],
    ['奇点临近', '库兹韦尔', '科技', 7.9, '技术指数级爆炸的预言'],
    ['癌症·真相', '李治中', '科技', 8.9, '科学认识癌症与疗法'],
    ['物种起源', '达尔文', '科技', 9.2, '自然选择的进化论奠基'],
    ['宇宙', '卡尔·萨根', '科技', 9.2, '仰望星空的诗意科普'],
    ['复杂', '梅拉妮·米歇尔', '科技', 8.6, '复杂性科学入门'],
    ['数学之美', '吴军', '科技', 8.9, '通信与语言中的数学'],
    ['人工智能简史', '尼克', '科技', 8.0, '从图灵测试到深度学习'],
    ['计算机网络：自顶向下方法', '库罗斯', '科技', 9.2, '网络分层原理经典教材'],
    ['黑客与画家', '保罗·格雷厄姆', '科技', 8.7, '编程与创造的思考'],
    ['编码', '查尔斯·佩措尔德', '科技', 9.1, '从电报到计算机的底层逻辑'],
    ['生命是什么', '薛定谔', '科技', 8.8, '物理学家眼中的生命本质'],
    ['算法图解', '巴尔加瓦', '科技', 8.8, '算法入门图解'],
    ['人件', '迪马尔科', '科技', 8.4, '软件开发的人本管理'],

    /* ===================== 哲学（20 本） ===================== */
    ['苏菲的世界', '乔斯坦·贾德', '哲学', 8.5, '一封封哲学启蒙信'],
    ['沉思录', '马可·奥勒留', '哲学', 8.6, '罗马皇帝的斯多葛自省'],
    ['理想国', '柏拉图', '哲学', 9.0, '正义与洞穴寓言的对话'],
    ['存在与时间', '海德格尔', '哲学', 8.8, '此在的生存论分析'],
    ['查拉图斯特拉如是说', '尼采', '哲学', 9.0, '超人哲学的散文诗'],
    ['西方哲学史', '罗素', '哲学', 8.9, '两千年思想脉络梳理'],
    ['中国哲学简史', '冯友兰', '哲学', 8.9, '儒道墨释的简明脉络'],
    ['纯粹理性批判', '康德', '哲学', 8.8, '认识何以可能的奠基'],
    ['尼各马可伦理学', '亚里士多德', '哲学', 9.0, '德性与幸福的目的论'],
    ['谈谈方法', '笛卡尔', '哲学', 8.6, '我思故我在的方法论'],
    ['逻辑哲学论', '维特根斯坦', '哲学', 8.7, '语言的界限即世界的界限'],
    ['第二性', '西蒙娜·德·波伏瓦', '哲学', 8.9, '女人之为他者的建构'],
    ['正义论', '罗尔斯', '哲学', 8.8, '作为公平的正义'],
    ['悲剧的诞生', '尼采', '哲学', 8.7, '日神与酒神的张力'],
    ['道德情操论', '亚当·斯密', '哲学', 8.9, '同理心是道德的根基'],
    ['规训与惩罚', '福柯', '哲学', 9.0, '监狱与权力的微观物理'],
    ['单向度的人', '马尔库塞', '哲学', 8.7, '发达工业社会的人性压抑'],
    ['哲学的故事', '杜兰特', '哲学', 8.7, '以人物串起哲学史'],
    ['作为意志和表象的世界', '叔本华', '哲学', 8.9, '生命意志与悲观哲思'],
    ['第一哲学沉思集', '笛卡尔', '哲学', 8.7, '怀疑方法的奠基'],

    /* ===================== 心理学（20 本） ===================== */
    ['心理学与生活', '津巴多', '心理学', 9.0, '经典入门通识教材'],
    ['思考，快与慢', '卡尼曼', '心理学', 8.8, '双系统思维与认知偏差'],
    ['乌合之众', '勒庞', '心理学', 8.4, '群体心理与盲从'],
    ['自卑与超越', '阿德勒', '心理学', 8.5, '个体心理学的自我超越'],
    ['梦的解析', '弗洛伊德', '心理学', 8.2, '潜意识与释梦的开山'],
    ['影响力', '罗伯特·西奥迪尼', '心理学', 8.6, '说服的六大原则'],
    ['社会性动物', '阿伦森', '心理学', 9.0, '社会心理学的经典'],
    ['被讨厌的勇气', '岸见一郎', '心理学', 8.6, '阿德勒哲学对话体'],
    ['非暴力沟通', '马歇尔·卢森堡', '心理学', 8.5, '观察感受需要的表达'],
    ['自控力', '凯利·麦格尼格尔', '心理学', 8.2, '意志力的科学'],
    ['怪诞行为学', '丹·艾瑞里', '心理学', 8.0, '非理性消费的实验'],
    ['亲密关系', '罗兰·米勒', '心理学', 9.0, '爱情与伴侣的科学'],
    ['活出意义来', '维克多·弗兰克尔', '心理学', 8.7, '集中营中的意义疗法'],
    ['心流', '米哈里·契克森米哈赖', '心理学', 8.3, '专注带来的最优体验'],
    ['少有人走的路', '斯科特·派克', '心理学', 8.4, '自律与心智成熟'],
    ['社会心理学', '戴维·迈尔斯', '心理学', 9.0, '权威教材全景'],
    ['改变心理学的40项研究', '罗杰·霍克', '心理学', 8.8, '经典实验串讲'],
    ['真实的幸福', '塞利格曼', '心理学', 8.2, '积极心理学的幸福模型'],
    ['刻意练习', '安德斯·艾利克森', '心理学', 8.0, '通往卓越的练习'],
    ['心智探奇', '史蒂芬·平克', '心理学', 8.6, '心智如何运作'],

    /* ===================== 经济（20 本） ===================== */
    ['国富论', '亚当·斯密', '经济', 9.0, '看不见的手与分工'],
    ['经济学原理', '曼昆', '经济', 9.1, '微观宏观入门经典'],
    ['贫穷的本质', '班纳吉', '经济', 8.4, '全球贫困的实地实验'],
    ['通往奴役之路', '哈耶克', '经济', 8.9, '计划经济的自由陷阱'],
    ['激荡三十年', '吴晓波', '经济', 8.5, '改革开放企业史'],
    ['薛兆丰经济学讲义', '薛兆丰', '经济', 8.5, '用经济学看日常'],
    ['大败局', '吴晓波', '经济', 8.3, '著名企业失败案例'],
    ['小狗钱钱', '博多·舍费尔', '经济', 8.9, '理财启蒙童话'],
    ['富爸爸穷爸爸', '清崎', '经济', 8.3, '资产与负债的财商课'],
    ['债：第一个5000年', '大卫·格雷伯', '经济', 8.6, '债务与文明的纠缠'],
    ['漫步华尔街', '马尔基尔', '经济', 8.3, '随机漫步投资指南'],
    ['周期', '霍华德·马克斯', '经济', 8.2, '投资周期与应对'],
    ['逃不开的经济周期', '拉斯·特维德', '经济', 8.2, '经济周期三百年'],
    ['斯坦福极简经济学', '泰勒·考恩', '经济', 8.3, '微观宏观速览'],
    ['小岛经济学', '彼得·希夫', '经济', 8.1, '寓言讲透通胀与危机'],
    ['聪明的投资者', '本杰明·格雷厄姆', '经济', 9.0, '价值投资圣经'],
    ['就业、利息和货币通论', '凯恩斯', '经济', 8.9, '宏观经济学奠基'],
    ['置身事内', '兰小欢', '经济', 8.9, '中国政府与经济发展'],
    ['经济与社会', '韦伯', '经济', 8.9, '经济社会学奠基'],
    ['资本主义与现代社会理论', '吉登斯', '经济', 8.5, '马克思韦伯涂尔干'],

    /* ===================== 艺术（20 本） ===================== */
    ['艺术的故事', '贡布里希', '艺术', 9.4, '从洞穴壁画到现代艺术'],
    ['美的历程', '李泽厚', '艺术', 9.0, '中国美学历史巡礼'],
    ['写给大家的中国美术史', '蒋勋', '艺术', 8.7, '简明中国美术脉络'],
    ['听音乐', '罗杰·卡门', '艺术', 9.0, '古典音乐欣赏指南'],
    ['设计中的设计', '原研哉', '艺术', 8.4, '无印良品的设计哲学'],
    ['简约至上', '贾尔斯·科尔伯恩', '艺术', 8.3, '交互设计的极简原则'],
    ['情感化设计', '唐纳德·诺曼', '艺术', 8.4, '本能行为反思三层次'],
    ['谈美', '朱光潜', '艺术', 9.0, '美感态度与生活'],
    ['摄影的艺术', '布鲁斯·巴恩博', '艺术', 8.8, '摄影构图与表达'],
    ['艺术与视知觉', '阿恩海姆', '艺术', 8.6, '格式塔心理学与艺术'],
    ['理解漫画', '斯科特·麦克劳德', '艺术', 8.8, '漫画语言的本质'],
    ['字体故事', '西蒙·加菲尔德', '艺术', 8.0, '关于字体的一切'],
    ['梵高传', '欧文·斯通', '艺术', 8.8, '燃烧生命的画家一生'],
    ['列奥纳多·达·芬奇传', '沃尔特·艾萨克森', '艺术', 8.7, '通才的天才解剖'],
    ['街道的美学', '芦原义信', '艺术', 8.4, '城市空间与街道尺度'],
    ['艺术通史', '史蒂芬·法辛', '艺术', 8.7, '全球艺术全景'],
    ['观看之道', '约翰·伯格', '艺术', 8.8, '图像与观看的政治'],
    ['中国建筑史', '梁思成', '艺术', 8.9, '中国古建流变梳理'],
    ['艺术与错觉', '贡布里希', '艺术', 8.9, '再现的心理机制'],
    ['人间词话', '王国维', '艺术', 9.0, '境界说的词学批评'],

    /* ===================== 传记（20 本） ===================== */
    ['史蒂夫·乔布斯传', '沃尔特·艾萨克森', '传记', 8.6, '苹果创始人的传奇一生'],
    ['苏东坡传', '林语堂', '传记', 8.6, '豁达文豪的跌宕人生'],
    ['曾国藩传', '张宏杰', '传记', 8.8, '晚清名臣的修身与功业'],
    ['邓小平时代', '傅高义', '传记', 9.0, '改革开放的设计与转折'],
    ['人类群星闪耀时', '茨威格', '传记', 8.7, '十四幕决定历史的瞬间'],
    ['贝多芬传', '罗曼·罗兰', '传记', 8.4, '扼住命运咽喉的乐圣'],
    ['富兰克林自传', '富兰克林', '传记', 8.4, '美国精神的自述典范'],
    ['渴望生活', '欧文·斯通', '传记', 9.0, '梵高燃烧的热望人生'],
    ['居里夫人传', '艾芙·居里', '传记', 8.6, '两获诺奖的科学伉俪'],
    ['马斯克传', '沃尔特·艾萨克森', '传记', 8.4, '颠覆者的野心与偏执'],
    ['别闹了，费曼先生', '费曼', '传记', 8.9, '科学顽童的率真自述'],
    ['昨日的世界', '茨威格', '传记', 8.9, '欧洲黄金时代的回忆'],
    ['王鼎钧回忆录', '王鼎钧', '传记', 9.0, '战乱流离的世纪回望'],
    ['约翰·克利斯朵夫', '罗曼·罗兰', '传记', 8.9, '音乐家精神成长小说'],
    ['毛泽东传', '罗斯·特里尔', '传记', 8.3, '革命者的一生评述'],
    ['爱因斯坦传', '沃尔特·艾萨克森', '传记', 8.6, '相对论的背后人生'],
    ['你当像鸟飞往你的山', '塔拉·韦斯特弗', '传记', 8.8, '教育挣脱原生家庭'],
    ['洛克菲勒自传', '洛克菲勒', '传记', 8.2, '石油大王的自述'],
    ['忏悔录', '卢梭', '传记', 8.6, '自我袒露的精神自传'],
    ['名人传', '罗曼·罗兰', '传记', 8.5, '贝多芬米开朗基罗托尔斯泰'],

    /* ===================== 散文（20 本） ===================== */
    ['朝花夕拾', '鲁迅', '散文', 9.0, '鲁迅温情的回忆散文'],
    ['目送', '龙应台', '散文', 8.7, '亲情与告别的三部曲'],
    ['病隙碎笔', '史铁生', '散文', 8.9, '苦难中的生命沉思'],
    ['我们仨', '杨绛', '散文', 8.7, '温润的家庭记忆'],
    ['撒哈拉的故事', '三毛', '散文', 8.8, '沙漠生活的率真记录'],
    ['我的阿勒泰', '李娟', '散文', 8.8, '新疆边地的明亮生活'],
    ['窗边的小豆豆', '黑柳彻子', '散文', 8.7, '巴学园里的童年'],
    ['沉默的大多数', '王小波', '散文', 9.0, '清醒理性的杂文随笔'],
    ['走到人生边上', '杨绛', '散文', 8.5, '对生死的追问'],
    ['文化苦旅', '余秋雨', '散文', 8.0, '山水间的文化寻根'],
    ['人间草木', '汪曾祺', '散文', 8.9, '草木鱼虫里的烟火气'],
    ['湘行散记', '沈从文', '散文', 8.6, '湘西水路的温情'],
    ['雅舍小品', '梁实秋', '散文', 8.5, '闲适幽默的生活散文'],
    ['各自的朝圣路', '周国平', '散文', 8.1, '哲思与人生的独白'],
    ['守望的距离', '周国平', '散文', 8.2, '关于爱与孤独的随笔'],
    ['把时间当作朋友', '李笑来', '散文', 8.2, '时间管理与自我成长'],
    ['皮囊', '蔡崇达', '散文', 8.0, '故乡与亲人的深情记录'],
    ['此生未完成', '于娟', '散文', 8.7, '病中的生命觉察'],
    ['缘缘堂随笔', '丰子恺', '散文', 8.8, '童心与人间情味'],
    ['也是冬天，也是春天', '迟子建', '散文', 8.2, '北国风物与生命'],

    /* ===================== 社会科学（20 本） ===================== */
    ['社会学想象力', '米尔斯', '社会科学', 9.0, '个人困扰与公共议题'],
    ['乡土中国', '费孝通', '社会科学', 9.2, '差序格局下的中国社会'],
    ['街角社会', '怀特', '社会科学', 8.6, '科纳维尔街区的田野'],
    ['自杀论', '涂尔干', '社会科学', 8.9, '社会事实解释自杀'],
    ['日常生活中的自我呈现', '戈夫曼', '社会科学', 8.8, '拟剧理论的面对面'],
    ['社会学的邀请', '乔恩·威特', '社会科学', 8.2, '社会学入门'],
    ['狂热分子', '埃里克·霍弗', '社会科学', 8.8, '群众运动的共性'],
    ['公正', '桑德尔', '社会科学', 8.9, '道德困境的公共思辨'],
    ['娱乐至死', '尼尔·波兹曼', '社会科学', 8.6, '媒介如何塑造文化'],
    ['童年的消逝', '尼尔·波兹曼', '社会科学', 8.1, '媒介侵蚀童年概念'],
    ['消费社会', '鲍德里亚', '社会科学', 8.4, '符号消费与拟像'],
    ['独自打保龄', '帕特南', '社会科学', 8.6, '美国社区资本的衰落'],
    ['不平等的代价', '斯蒂格利茨', '社会科学', 8.0, '贫富分化伤害所有人'],
    ['与社会学同游', '彼得·伯格', '社会科学', 8.7, '社会学的慧眼'],
    ['厌女', '上野千鹤子', '社会科学', 8.4, '日本社会的性别歧视结构'],
    ['父权制与资本主义', '上野千鹤子', '社会科学', 8.6, '双重压迫的剖析'],
    ['弱者的武器', '詹姆斯·斯科特', '社会科学', 8.6, '农民日常反抗'],
    ['现实的社会建构', '伯格', '社会科学', 8.7, '知识社会学的奠基'],
    ['金翼', '林耀华', '社会科学', 8.6, '中国家族的田野小说'],
    ['江村经济', '费孝通', '社会科学', 8.9, '中国乡村的经济调查']
  ];

  /* === AUTO COVERS START === */
  // 由一次性构建脚本生成：本地真实封面(assets/covers/) + 真实 subject 链接。可重跑更新。
  const COVERS = {
    '1453': { cover: 'assets/covers/cover_48.jpg', douban: '' },
    '1984': { cover: 'assets/covers/cover_8.jpg', douban: '' },
    '百年孤独': { cover: 'assets/covers/cover_0.jpg', douban: '' },
    '活着': { cover: 'assets/covers/cover_1.jpg', douban: '' },
    '追风筝的人': { cover: 'assets/covers/cover_2.jpg', douban: '' },
    '了不起的盖茨比': { cover: 'assets/covers/cover_3.jpg', douban: '' },
    '围城': { cover: 'assets/covers/cover_4.jpg', douban: '' },
    '平凡的世界': { cover: 'assets/covers/cover_5.jpg', douban: '' },
    '三体': { cover: 'assets/covers/cover_6.jpg', douban: '' },
    '红楼梦': { cover: 'assets/covers/cover_7.jpg', douban: '' },
    '霍乱时期的爱情': { cover: 'assets/covers/cover_9.jpg', douban: '' },
    '飘': { cover: 'assets/covers/cover_10.jpg', douban: '' },
    '卡拉马佐夫兄弟': { cover: 'assets/covers/cover_11.jpg', douban: '' },
    '老人与海': { cover: 'assets/covers/cover_12.jpg', douban: '' },
    '麦田里的守望者': { cover: 'assets/covers/cover_13.jpg', douban: '' },
    '挪威的森林': { cover: 'assets/covers/cover_14.jpg', douban: '' },
    '白夜行': { cover: 'assets/covers/cover_15.jpg', douban: '' },
    '解忧杂货店': { cover: 'assets/covers/cover_16.jpg', douban: '' },
    '小王子': { cover: 'assets/covers/cover_17.jpg', douban: '' },
    '悲惨世界': { cover: 'assets/covers/cover_18.jpg', douban: '' },
    '安娜·卡列尼娜': { cover: 'assets/covers/cover_19.jpg', douban: '' },
    '骆驼祥子': { cover: 'assets/covers/cover_20.jpg', douban: '' },
    '边城': { cover: 'assets/covers/cover_21.jpg', douban: '' },
    '战争与和平': { cover: 'assets/covers/cover_22.jpg', douban: '' },
    '檀香刑': { cover: 'assets/covers/cover_23.jpg', douban: '' },
    '长恨歌': { cover: 'assets/covers/cover_24.jpg', douban: '' },
    '许三观卖血记': { cover: 'assets/covers/cover_25.jpg', douban: '' },
    '兄弟': { cover: 'assets/covers/cover_26.jpg', douban: '' },
    '人类简史': { cover: 'assets/covers/cover_27.jpg', douban: '' },
    '万历十五年': { cover: 'assets/covers/cover_28.jpg', douban: '' },
    '明朝那些事儿': { cover: 'assets/covers/cover_29.jpg', douban: '' },
    '史记': { cover: 'assets/covers/cover_30.jpg', douban: '' },
    '资治通鉴': { cover: 'assets/covers/cover_31.jpg', douban: '' },
    '枪炮、病菌与钢铁': { cover: 'assets/covers/cover_32.jpg', douban: '' },
    '全球通史': { cover: 'assets/covers/cover_33.jpg', douban: '' },
    '中国历代政治得失': { cover: 'assets/covers/cover_34.jpg', douban: '' },
    '罗马人的故事': { cover: 'assets/covers/cover_35.jpg', douban: '' },
    '大秦帝国': { cover: 'assets/covers/cover_36.jpg', douban: '' },
    '中国大历史': { cover: 'assets/covers/cover_37.jpg', douban: '' },
    '战争史': { cover: 'assets/covers/cover_38.jpg', douban: '' },
    '叫魂': { cover: 'assets/covers/cover_39.jpg', douban: '' },
    '第二次世界大战战史': { cover: 'assets/covers/cover_40.jpg', douban: '' },
    '大国的兴衰': { cover: 'assets/covers/cover_41.jpg', douban: '' },
    '菊花与刀': { cover: 'assets/covers/cover_42.jpg', douban: '' },
    '旧制度与大革命': { cover: 'assets/covers/cover_43.jpg', douban: '' },
    '丝绸之路': { cover: 'assets/covers/cover_44.jpg', douban: '' },
    '国史大纲': { cover: 'assets/covers/cover_45.jpg', douban: '' },
    '天朝的崩溃': { cover: 'assets/covers/cover_46.jpg', douban: '' },
    '罗马帝国衰亡史': { cover: 'assets/covers/cover_47.jpg', douban: '' },
    '时间简史': { cover: 'assets/covers/cover_49.jpg', douban: '' },
    '自私的基因': { cover: 'assets/covers/cover_50.jpg', douban: '' },
    '未来简史': { cover: 'assets/covers/cover_51.jpg', douban: '' },
    '上帝掷骰子吗：量子物理史话': { cover: 'assets/covers/cover_52.jpg', douban: '' },
    '从一到无穷大': { cover: 'assets/covers/cover_53.jpg', douban: '' },
    '浪潮之巅': { cover: 'assets/covers/cover_54.jpg', douban: '' },
    '人月神话': { cover: 'assets/covers/cover_55.jpg', douban: '' },
    '代码大全': { cover: 'assets/covers/cover_56.jpg', douban: '' },
    '失控': { cover: 'assets/covers/cover_57.jpg', douban: '' },
    '奇点临近': { cover: 'assets/covers/cover_58.jpg', douban: '' },
    '癌症·真相': { cover: 'assets/covers/cover_59.jpg', douban: '' },
    '物种起源': { cover: 'assets/covers/cover_60.jpg', douban: '' },
    '宇宙': { cover: 'assets/covers/cover_61.jpg', douban: '' },
    '复杂': { cover: 'assets/covers/cover_62.jpg', douban: '' },
    '数学之美': { cover: 'assets/covers/cover_63.jpg', douban: '' },
    '人工智能简史': { cover: 'assets/covers/cover_64.jpg', douban: '' },
    '计算机网络：自顶向下方法': { cover: 'assets/covers/cover_65.jpg', douban: '' },
    '黑客与画家': { cover: 'assets/covers/cover_66.jpg', douban: '' },
    '编码': { cover: 'assets/covers/cover_67.jpg', douban: '' },
    '生命是什么': { cover: 'assets/covers/cover_68.jpg', douban: '' },
    '算法图解': { cover: 'assets/covers/cover_69.jpg', douban: '' },
    '人件': { cover: 'assets/covers/cover_70.jpg', douban: '' },
    '苏菲的世界': { cover: 'assets/covers/cover_71.jpg', douban: '' },
    '沉思录': { cover: 'assets/covers/cover_72.jpg', douban: '' },
    '理想国': { cover: 'assets/covers/cover_73.jpg', douban: '' },
    '存在与时间': { cover: 'assets/covers/cover_74.jpg', douban: '' },
    '查拉图斯特拉如是说': { cover: 'assets/covers/cover_75.jpg', douban: '' },
    '西方哲学史': { cover: 'assets/covers/cover_76.jpg', douban: '' },
    '中国哲学简史': { cover: 'assets/covers/cover_77.jpg', douban: '' },
    '纯粹理性批判': { cover: 'assets/covers/cover_78.jpg', douban: '' },
    '尼各马可伦理学': { cover: 'assets/covers/cover_79.jpg', douban: '' },
    '谈谈方法': { cover: 'assets/covers/cover_80.jpg', douban: '' },
    '逻辑哲学论': { cover: 'assets/covers/cover_81.jpg', douban: '' },
    '第二性': { cover: 'assets/covers/cover_82.jpg', douban: '' },
    '正义论': { cover: 'assets/covers/cover_83.jpg', douban: '' },
    '悲剧的诞生': { cover: 'assets/covers/cover_84.jpg', douban: '' },
    '道德情操论': { cover: 'assets/covers/cover_85.jpg', douban: '' },
    '规训与惩罚': { cover: 'assets/covers/cover_86.jpg', douban: '' },
    '单向度的人': { cover: 'assets/covers/cover_87.jpg', douban: '' },
    '哲学的故事': { cover: 'assets/covers/cover_88.jpg', douban: '' },
    '作为意志和表象的世界': { cover: 'assets/covers/cover_89.jpg', douban: '' },
    '第一哲学沉思集': { cover: 'assets/covers/cover_90.jpg', douban: '' },
    '心理学与生活': { cover: 'assets/covers/cover_91.jpg', douban: '' },
    '思考，快与慢': { cover: 'assets/covers/cover_92.jpg', douban: '' },
    '乌合之众': { cover: 'assets/covers/cover_93.jpg', douban: '' },
    '自卑与超越': { cover: 'assets/covers/cover_94.jpg', douban: '' },
    '梦的解析': { cover: 'assets/covers/cover_95.jpg', douban: '' },
    '影响力': { cover: 'assets/covers/cover_96.jpg', douban: '' },
    '社会性动物': { cover: 'assets/covers/cover_97.jpg', douban: '' },
    '被讨厌的勇气': { cover: 'assets/covers/cover_98.jpg', douban: '' },
    '非暴力沟通': { cover: 'assets/covers/cover_99.jpg', douban: '' },
    '自控力': { cover: 'assets/covers/cover_100.jpg', douban: '' },
    '怪诞行为学': { cover: 'assets/covers/cover_101.jpg', douban: '' },
    '亲密关系': { cover: 'assets/covers/cover_102.jpg', douban: '' },
    '活出意义来': { cover: 'assets/covers/cover_103.jpg', douban: '' },
    '心流': { cover: 'assets/covers/cover_104.jpg', douban: '' },
    '少有人走的路': { cover: 'assets/covers/cover_105.jpg', douban: '' },
    '社会心理学': { cover: 'assets/covers/cover_106.jpg', douban: '' },
    '改变心理学的40项研究': { cover: 'assets/covers/cover_107.jpg', douban: '' },
    '真实的幸福': { cover: 'assets/covers/cover_108.jpg', douban: '' },
    '刻意练习': { cover: 'assets/covers/cover_109.jpg', douban: '' },
    '心智探奇': { cover: 'assets/covers/cover_110.jpg', douban: '' },
    '国富论': { cover: 'assets/covers/cover_111.jpg', douban: '' },
    '经济学原理': { cover: 'assets/covers/cover_112.jpg', douban: '' },
    '贫穷的本质': { cover: 'assets/covers/cover_113.jpg', douban: '' },
    '通往奴役之路': { cover: 'assets/covers/cover_114.jpg', douban: '' },
    '激荡三十年': { cover: 'assets/covers/cover_115.jpg', douban: '' },
    '薛兆丰经济学讲义': { cover: 'assets/covers/cover_116.jpg', douban: '' },
    '大败局': { cover: 'assets/covers/cover_117.jpg', douban: '' },
    '小狗钱钱': { cover: 'assets/covers/cover_118.jpg', douban: '' },
    '富爸爸穷爸爸': { cover: 'assets/covers/cover_119.jpg', douban: '' },
    '债：第一个5000年': { cover: 'assets/covers/cover_120.jpg', douban: '' },
    '漫步华尔街': { cover: 'assets/covers/cover_121.jpg', douban: '' },
    '周期': { cover: 'assets/covers/cover_122.jpg', douban: '' },
    '逃不开的经济周期': { cover: 'assets/covers/cover_123.jpg', douban: '' },
    '斯坦福极简经济学': { cover: 'assets/covers/cover_124.jpg', douban: '' },
    '小岛经济学': { cover: 'assets/covers/cover_125.jpg', douban: '' },
    '聪明的投资者': { cover: 'assets/covers/cover_126.jpg', douban: '' },
    '就业、利息和货币通论': { cover: 'assets/covers/cover_127.jpg', douban: '' },
    '置身事内': { cover: 'assets/covers/cover_128.jpg', douban: '' },
    '经济与社会': { cover: 'assets/covers/cover_129.jpg', douban: '' },
    '资本主义与现代社会理论': { cover: 'assets/covers/cover_130.jpg', douban: '' },
    '艺术的故事': { cover: 'assets/covers/cover_131.jpg', douban: '' },
    '美的历程': { cover: 'assets/covers/cover_132.jpg', douban: '' },
    '写给大家的中国美术史': { cover: 'assets/covers/cover_133.jpg', douban: '' },
    '听音乐': { cover: 'assets/covers/cover_134.jpg', douban: '' },
    '设计中的设计': { cover: 'assets/covers/cover_135.jpg', douban: '' },
    '简约至上': { cover: 'assets/covers/cover_136.jpg', douban: '' },
    '情感化设计': { cover: 'assets/covers/cover_137.jpg', douban: '' },
    '谈美': { cover: 'assets/covers/cover_138.jpg', douban: '' },
    '摄影的艺术': { cover: 'assets/covers/cover_139.jpg', douban: '' },
    '艺术与视知觉': { cover: 'assets/covers/cover_140.jpg', douban: '' },
    '理解漫画': { cover: 'assets/covers/cover_141.jpg', douban: '' },
    '字体故事': { cover: 'assets/covers/cover_142.jpg', douban: '' },
    '梵高传': { cover: 'assets/covers/cover_143.jpg', douban: '' },
    '列奥纳多·达·芬奇传': { cover: 'assets/covers/cover_144.jpg', douban: '' },
    '街道的美学': { cover: 'assets/covers/cover_145.jpg', douban: '' },
    '艺术通史': { cover: 'assets/covers/cover_146.jpg', douban: '' },
    '观看之道': { cover: 'assets/covers/cover_147.jpg', douban: '' },
    '中国建筑史': { cover: 'assets/covers/cover_148.jpg', douban: '' },
    '艺术与错觉': { cover: 'assets/covers/cover_149.jpg', douban: '' },
    '人间词话': { cover: 'assets/covers/cover_150.jpg', douban: '' },
    '史蒂夫·乔布斯传': { cover: 'assets/covers/cover_151.jpg', douban: '' },
    '苏东坡传': { cover: 'assets/covers/cover_152.jpg', douban: '' },
    '曾国藩传': { cover: 'assets/covers/cover_153.jpg', douban: '' },
    '邓小平时代': { cover: 'assets/covers/cover_154.jpg', douban: '' },
    '人类群星闪耀时': { cover: 'assets/covers/cover_155.jpg', douban: '' },
    '贝多芬传': { cover: 'assets/covers/cover_156.jpg', douban: '' },
    '富兰克林自传': { cover: 'assets/covers/cover_157.jpg', douban: '' },
    '渴望生活': { cover: 'assets/covers/cover_158.jpg', douban: '' },
    '居里夫人传': { cover: 'assets/covers/cover_159.jpg', douban: '' },
    '马斯克传': { cover: 'assets/covers/cover_160.jpg', douban: '' },
    '别闹了，费曼先生': { cover: 'assets/covers/cover_161.jpg', douban: '' },
    '昨日的世界': { cover: 'assets/covers/cover_162.jpg', douban: '' },
    '王鼎钧回忆录': { cover: 'assets/covers/cover_163.jpg', douban: '' },
    '约翰·克利斯朵夫': { cover: 'assets/covers/cover_164.jpg', douban: '' },
    '毛泽东传': { cover: 'assets/covers/cover_165.jpg', douban: '' },
    '爱因斯坦传': { cover: 'assets/covers/cover_166.jpg', douban: '' },
    '你当像鸟飞往你的山': { cover: 'assets/covers/cover_167.jpg', douban: '' },
    '洛克菲勒自传': { cover: 'assets/covers/cover_168.jpg', douban: '' },
    '忏悔录': { cover: 'assets/covers/cover_169.jpg', douban: '' },
    '名人传': { cover: 'assets/covers/cover_170.jpg', douban: '' },
    '朝花夕拾': { cover: 'assets/covers/cover_171.jpg', douban: '' },
    '目送': { cover: 'assets/covers/cover_172.jpg', douban: '' },
    '病隙碎笔': { cover: 'assets/covers/cover_173.jpg', douban: '' },
    '我们仨': { cover: 'assets/covers/cover_174.jpg', douban: '' },
    '撒哈拉的故事': { cover: 'assets/covers/cover_175.jpg', douban: '' },
    '我的阿勒泰': { cover: 'assets/covers/cover_176.jpg', douban: '' },
    '窗边的小豆豆': { cover: 'assets/covers/cover_177.jpg', douban: '' },
    '沉默的大多数': { cover: 'assets/covers/cover_178.jpg', douban: '' },
    '走到人生边上': { cover: 'assets/covers/cover_179.jpg', douban: '' },
    '文化苦旅': { cover: 'assets/covers/cover_180.jpg', douban: '' },
    '人间草木': { cover: 'assets/covers/cover_181.jpg', douban: '' },
    '湘行散记': { cover: 'assets/covers/cover_182.jpg', douban: '' },
    '雅舍小品': { cover: 'assets/covers/cover_183.jpg', douban: '' },
    '各自的朝圣路': { cover: 'assets/covers/cover_184.jpg', douban: '' },
    '守望的距离': { cover: 'assets/covers/cover_185.jpg', douban: '' },
    '把时间当作朋友': { cover: 'assets/covers/cover_186.jpg', douban: '' },
    '皮囊': { cover: 'assets/covers/cover_187.jpg', douban: '' },
    '此生未完成': { cover: 'assets/covers/cover_188.jpg', douban: '' },
    '缘缘堂随笔': { cover: 'assets/covers/cover_189.jpg', douban: '' },
    '也是冬天，也是春天': { cover: 'assets/covers/cover_190.jpg', douban: '' },
    '社会学想象力': { cover: 'assets/covers/cover_191.jpg', douban: '' },
    '乡土中国': { cover: 'assets/covers/cover_192.jpg', douban: '' },
    '街角社会': { cover: 'assets/covers/cover_193.jpg', douban: '' },
    '自杀论': { cover: 'assets/covers/cover_194.jpg', douban: '' },
    '日常生活中的自我呈现': { cover: 'assets/covers/cover_195.jpg', douban: '' },
    '社会学的邀请': { cover: 'assets/covers/cover_196.jpg', douban: '' },
    '狂热分子': { cover: 'assets/covers/cover_197.jpg', douban: '' },
    '公正': { cover: 'assets/covers/cover_198.jpg', douban: '' },
    '娱乐至死': { cover: 'assets/covers/cover_199.jpg', douban: '' },
    '童年的消逝': { cover: 'assets/covers/cover_200.jpg', douban: '' },
    '消费社会': { cover: 'assets/covers/cover_201.jpg', douban: '' },
    '独自打保龄': { cover: 'assets/covers/cover_202.jpg', douban: '' },
    '不平等的代价': { cover: 'assets/covers/cover_203.jpg', douban: '' },
    '与社会学同游': { cover: 'assets/covers/cover_204.jpg', douban: '' },
    '厌女': { cover: 'assets/covers/cover_205.jpg', douban: '' },
    '父权制与资本主义': { cover: 'assets/covers/cover_206.jpg', douban: '' },
    '弱者的武器': { cover: 'assets/covers/cover_207.jpg', douban: '' },
    '现实的社会建构': { cover: 'assets/covers/cover_208.jpg', douban: '' },
    '金翼': { cover: 'assets/covers/cover_209.jpg', douban: '' },
    '江村经济': { cover: 'assets/covers/cover_210.jpg', douban: '' }
  };
  /* === AUTO COVERS END === */

  // 取某本书的封面 / 豆瓣链接：优先用抓到的真实数据，缺失则回退
  function coverOf(title) {
    var c = COVERS[title];
    return c && c.cover ? c.cover : '';
  }
  function doubanOf(title) {
    var c = COVERS[title];
    return c && c.douban ? c.douban : doubanUrl(title);
  }

  // 转换为标准对象，并补全链接字段
  const BOOKS = RAW.map(function (row) {
    const title = row[0];
    return {
      title: title,
      author: row[1],
      cover: coverOf(title),    // 真实豆瓣封面；缺失则为 ''（渲染时显示占位封面）
      summary: row[4],
      rating: row[3],
      category: row[2],
      doubanUrl: doubanOf(title), // 真实 subject 链接，缺失则回退豆瓣搜索页
      wereadSearchUrl: wereadSearchUrl(title)
    };
  });

  // 暴露到全局，供 bookRecommend.js / 其他脚本使用
  window.BOOKS = BOOKS;

  // 便于调试：控制台打印总数（可删）
  if (window.console && console.log) {
    console.log('[books.js] 已加载预置书库，共 ' + BOOKS.length + ' 本');
  }
})();
