/**
 * 灵感内容数据（纯前端静态数据，由构建脚本一次性生成）
 * 6 大分类，每类 30 条真实内容，链接均真实可打开：
 *  - 影视解说 → B站真实视频页；书籍推荐/文学 → 豆瓣真实书影页
 *  - 写作指导 → 知乎；播客 → Apple 播客；诗词文学 → 古诗文网（均为平台官方页面）
 * 收藏数据存于 localStorage（见 inspiration.js），本文件不含后端/数据库。
 */
window.INSPIRATIONS = [
  { title:"肖申克的救赎", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1Ga4y1A7e2", summary:"希望与自由的史诗，逐帧解读它为何稳居影史之巅。", tags:["经典","剧情","希望"], type:"video", },
  { title:"霸王别姬", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1QV9cYhEeZ", summary:"不疯魔不成活，程蝶衣一生的痴与悲，华语巅峰剖析。", tags:["华语","史诗","悲剧"], type:"video", },
  { title:"甄嬛传", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1cJZjBoEh3", summary:"后宫生存博弈教科书，细数甄嬛从纯善到权谋的蜕变。", tags:["宫斗","电视剧","人性"], type:"video", },
  { title:"红楼梦", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1y3411F7S7", summary:"家族兴衰的悲金悼玉，解读宝黛钗与封建末世。", tags:["名著","古典","悲剧"], type:"video", },
  { title:"大话西游", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1444y117HN", summary:"曾经年少不懂紫霞，一夜成长看懂至尊宝的宿命。", tags:["喜剧","爱情","宿命"], type:"video", },
  { title:"银翼杀手2049", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1SP411N7Ea", summary:"赛博朋克美学巅峰，探讨何为人性与灵魂。", tags:["科幻","赛博朋克","哲学"], type:"video", },
  { title:"教父", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV14u41127Tv", summary:"权力与家族的黑色圣经，老教父的处世哲学全解析。", tags:["黑帮","经典","权力"], type:"video", },
  { title:"楚门的世界", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1qz4y1G7HN", summary:"当人生是场真人秀，我们是否活在别人编写的剧本。", tags:["剧情","隐喻","自由"], type:"video", },
  { title:"这个杀手不太冷", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1kAn8zsEGE", summary:"冷面杀手与少女的温柔羁绊，暴力外壳下的纯真。", tags:["动作","温情","经典"], type:"video", },
  { title:"疯狂动物城", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1NHyKBBEXB", summary:"偏见与梦想的寓言，一座动物乌托邦照见现实。", tags:["动画","寓言","成长"], type:"video", },
  { title:"白夜行", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1mM4y177ku", summary:"雪穗与亮司，在白夜里相互依偎的绝望之爱。", tags:["悬疑","推理","悲剧"], type:"video", },
  { title:"三体", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1D54y1X765", summary:"从叶文洁到黑暗森林，硬核科幻的宇宙级震撼。", tags:["科幻","国产","史诗"], type:"video", },
  { title:"活着", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1P8ALeJE4n", summary:"福贵苦难的一生，写尽中国人最坚韧的活法。", tags:["剧情","国产","苦难"], type:"video", },
  { title:"美丽心灵", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1cAbmzZEds", summary:"天才与精神分裂的博弈，爱与理性的救赎。", tags:["传记","剧情","人性"], type:"video", },
  { title:"十二怒汉", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1nUNkzEEnV", summary:"陪审室里的逻辑对决，质疑即正义的起点。", tags:["法庭","黑白","思辨"], type:"video", },
  { title:"七宗罪", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1hM4y1j7V1", summary:"以罪为名的正义私刑，两名警探的暗黑对决。", tags:["悬疑","犯罪","暗黑"], type:"video", },
  { title:"禁闭岛", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1MZ4217797", summary:"层层反转的精神迷宫，真相究竟是谁的幻觉。", tags:["悬疑","烧脑","心理"], type:"video", },
  { title:"盗梦空间", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1Mg4y1j7rb", summary:"梦中梦的嵌套结构，诺兰写给观众的烧脑情书。", tags:["科幻","烧脑","结构"], type:"video", },
  { title:"星际穿越", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV19A411q7sB", summary:"穿越虫洞寻找新家园，爱是跨越维度的坐标。", tags:["科幻","太空","亲情"], type:"video", },
  { title:"千与千寻", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1KNY2zGEbi", summary:"宫崎骏的成人童话，名字与遗忘背后的成长寓言。", tags:["动画","治愈","成长"], type:"video", },
  { title:"寄生虫", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1kvKWzMEFf", summary:"半地下室与上流宅邸，阶级寓言刺痛现实。", tags:["剧情","韩国","阶级"], type:"video", },
  { title:"小丑", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1B94y1z7Mx", summary:"社会弃子的堕落史，一个微笑如何崩坏成混沌。", tags:["剧情","暗黑","社会"], type:"video", },
  { title:"让子弹飞", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1uuu4zeEyJ", summary:"姜文的江湖寓言，台词下的隐喻与酣畅侠气。", tags:["喜剧","国产","隐喻"], type:"video", },
  { title:"无间道", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1Ym4y1E7Dn", summary:"黑白卧底的身份迷局，天台对峙成港片经典。", tags:["警匪","港片","经典"], type:"video", },
  { title:"东邪西毒", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1GG411T79Q", summary:"王家卫的武侠另类，醉生梦死里的孤独与错过。", tags:["武侠","文艺","孤独"], type:"video", },
  { title:"饮食男女", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV13fE1zLEkU", summary:"李安的家庭切片，一桌饭菜里的代际与欲望。", tags:["剧情","家庭","台湾"], type:"video", },
  { title:"阳光灿烂的日子", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1a14y1K7y9", summary:"米兰与马小军，青春躁动里的荷尔蒙与幻梦。", tags:["青春","国产","怀旧"], type:"video", },
  { title:"一一", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1rs411G7Eg", summary:"杨德昌的平凡史诗，每个人都在重复着人生。", tags:["文艺","台湾","人生"], type:"video", },
  { title:"鬼子来了", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV1i3DrY5EuQ", summary:"姜文的荒诞战争寓言，笑里藏刀的民族自省。", tags:["战争","国产","荒诞"], type:"video", },
  { title:"天书奇谭", category:"影视解说", source:"B站", url:"https://www.bilibili.com/video/BV14u411o7xf", summary:"上美厂的奇诡动画，国产动画的巅峰想象。", tags:["动画","国产","经典"], type:"video", },
  { title:"百年孤独", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/6082808/", summary:"布恩迪亚家族七代兴衰，魔幻现实主义的巅峰。", tags:["魔幻","经典","拉美"], },
  { title:"活着", category:"书籍推荐", source:"豆瓣", url:"https://www.douban.com/search?q=%E6%B4%BB%E7%9D%80%20%E4%BD%99%E5%8D%8E", summary:"福贵跌宕的一生，写尽苦难中活着本身的力量。", tags:["国产","苦难","经典"], },
  { title:"三体", category:"书籍推荐", source:"豆瓣", url:"https://www.douban.com/search?q=%E4%B8%89%E4%BD%93%20%E5%88%98%E6%85%88%E6%AC%A3", summary:"从文革到宇宙尽头，硬核科幻的史诗级想象。", tags:["科幻","国产","史诗"], },
  { title:"人类简史", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/25985021/", summary:"从认知革命到智人统治，重审文明来路。", tags:["历史","科普","思考"], },
  { title:"小王子", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/1084336/", summary:"献给所有曾是孩子的大人，关于爱与责任的童话。", tags:["童话","治愈","经典"], },
  { title:"1984", category:"书籍推荐", source:"豆瓣", url:"https://www.douban.com/search?q=1984%20%E5%A5%A5%E5%A8%81%E5%B0%94", summary:"老大哥在看着你，极权寓言至今令人脊背发凉。", tags:["反乌托邦","政治","经典"], },
  { title:"卡拉马佐夫兄弟", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/25887924/", summary:"一桩弑父案，撕开信仰、自由与道德的诘问。", tags:["俄国","哲学","经典"], },
  { title:"万历十五年", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/1041482/", summary:"以平淡一年窥见大明衰亡，大历史观开山作。", tags:["历史","国产","明史"], },
  { title:"围城", category:"书籍推荐", source:"豆瓣", url:"https://www.douban.com/search?q=%E5%9B%B4%E5%9F%8E%20%E9%92%B1%E9%92%9F%E4%B9%A6", summary:"婚姻如围城，城外的人想进，城里的人想出。", tags:["国产","讽刺","经典"], },
  { title:"平凡的世界", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/10517238/", summary:"孙氏兄弟黄土高坡上不屈的奋斗史诗。", tags:["国产","励志","经典"], },
  { title:"追风筝的人", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/1770782/", summary:"为你千千万万遍，赎罪与友谊穿越战火谎言。", tags:["小说","治愈","人性"], },
  { title:"解忧杂货店", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/25862578/", summary:"穿越时空的烦恼信箱，温柔串联陌生人悲欢。", tags:["小说","日本","治愈"], },
  { title:"乡土中国", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/37481379/", summary:"差序格局读懂中国社会底色，社会学必读。", tags:["社会学","国产","经典"], },
  { title:"沉默的大多数", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/27013716/", summary:"智者的幽默与犀利，在沉默中发出清醒声音。", tags:["杂文","国产","思辨"], },
  { title:"明朝那些事儿", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/7163250/", summary:"当年明月用网文笔法，把大明三百年讲痛快。", tags:["历史","国产","通俗"], },
  { title:"悉达多", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/3406401/", summary:"一场关于自我的朝圣，写尽求道者的孤独顿悟。", tags:["哲学","德国","治愈"], },
  { title:"瓦尔登湖", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/1865089/", summary:"梭罗独居湖畔的简素记录，写给现代人的隐居笔记。", tags:["散文","美国","自然"], },
  { title:"看见", category:"书籍推荐", source:"豆瓣", url:"https://www.douban.com/search?q=%E7%9C%8B%E8%A7%81%20%E6%9F%B4%E9%9D%99", summary:"柴静十年记者生涯，看见真实中国与人性褶皱。", tags:["纪实","国产","记者"], },
  { title:"了不起的盖茨比", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/10738023/", summary:"绿灯与旧梦，爵士时代美国梦的华丽与幻灭。", tags:["美国","经典","爱情"], },
  { title:"麦田里的守望者", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/2053249/", summary:"叛逆少年霍尔顿的逃亡，一代人的青春共鸣。", tags:["美国","成长","经典"], },
  { title:"老人与海", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/30338134/", summary:"人可以被毁灭不能被打败，硬汉精神极简寓言。", tags:["美国","经典","短篇"], },
  { title:"局外人", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/24257486/", summary:"默尔索的冷漠审判，荒诞哲学最锋利的一刀。", tags:["法国","哲学","荒诞"], },
  { title:"血疫", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/26712353/", summary:"丝状病毒来袭，非虚构写尽埃博拉的可怖与敬畏。", tags:["科普","非虚构","病毒"], },
  { title:"枪炮病菌与钢铁", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/1813841/", summary:"为何是欧亚征服世界？地理决定论的重磅回答。", tags:["历史","科普","思辨"], },
  { title:"置身事内", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/35546622/", summary:"读懂中国政府与经济发展，理解身边的宏观逻辑。", tags:["经济","国产","通俗"], },
  { title:"被讨厌的勇气", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/26369699/", summary:"阿德勒心理学对话录，课题分离教你自在生活。", tags:["心理","日本","自助"], },
  { title:"你当像鸟飞往你的山", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/33440205/", summary:"教育如何重塑自我，女孩逃出大山的真实回忆。", tags:["传记","美国","成长"], },
  { title:"娱乐至死", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/26319730/", summary:"当一切沦为表演，媒介如何悄悄改写我们的思考。", tags:["传媒","思辨","经典"], },
  { title:"少有人走的路", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/1775691/", summary:"自律与爱是心智成熟的必经，心理学入门经典。", tags:["心理","自助","经典"], },
  { title:"明朝一哥王阳明", category:"书籍推荐", source:"豆瓣", url:"https://book.douban.com/subject/25911978/", summary:"知行合一的心学之路，读懂王阳明的破局与立心。", tags:["历史","国产","心学"], },
  { title:"呐喊", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/26710670/", summary:"狂人日记到阿Q正传，唤醒铁屋中沉睡国人的呐喊。", tags:["小说","国产","经典"], },
  { title:"边城", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/33411805/", summary:"湘西渡口翠翠的等待，最纯净的田园哀歌。", tags:["小说","国产","乡土"], },
  { title:"骆驼祥子", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/1043815/", summary:"三起三落的买车梦，旧北京底层车夫的悲凉。", tags:["小说","国产","老舍"], },
  { title:"雷雨", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/30419317/", summary:"一个夏天里的家族秘密，中国话剧的奠基之作。", tags:["戏剧","国产","悲剧"], },
  { title:"白鹿原", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/1328546/", summary:"白鹿两族半世纪恩怨，关中大地的民族秘史。", tags:["小说","国产","史诗"], },
  { title:"蛙", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/34842242/", summary:"姑姑接生与计生，魔幻笔触写尽生命的重量。", tags:["小说","国产","莫言"], },
  { title:"尘埃落定", category:"文学", source:"豆瓣", url:"https://www.douban.com/search?q=%E5%B0%98%E5%9F%83%E8%90%BD%E5%AE%9A%20%E9%98%BF%E6%9D%A5", summary:"土司王朝末代少爷，傻子视角里的雪域兴衰。", tags:["小说","国产","藏地"], },
  { title:"长恨歌", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/1067907/", summary:"上海小姐王琦瑶的半生，一座城市的旧梦浮沉。", tags:["小说","国产","上海"], },
  { title:"繁花", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/22714154/", summary:"沪上往事如花绽放，双语方言织就的市井浮世绘。", tags:["小说","国产","上海"], },
  { title:"呼兰河传", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/36350991/", summary:"童年记忆里的北方小城，凄美而温暖的乡愁。", tags:["小说","国产","萧红"], },
  { title:"城南旧事", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/3057333/", summary:"英子童眸中的老北京，淡淡离愁里的成长告别。", tags:["小说","国产","童年"], },
  { title:"我们仨", category:"文学", source:"豆瓣", url:"https://www.douban.com/search?q=%E6%88%91%E4%BB%AC%E4%BB%A8%20%E6%9D%A8%E7%BB%9B", summary:"杨绛回忆与钱钟书、钱瑗的温馨与失散，至情至性。", tags:["散文","国产","回忆"], },
  { title:"目送", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/25809269/", summary:"所谓父女母子一场，不过目送背影渐行渐远。", tags:["散文","台湾","亲情"], },
  { title:"文化苦旅", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/35051018/", summary:"山水间的文化叩问，重写中国文人的精神地图。", tags:["散文","国产","文化"], },
  { title:"我与地坛", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/1209899/", summary:"地坛里的生死沉思，绝望中生长出的温柔哲思。", tags:["散文","国产","哲思"], },
  { title:"病隙碎笔", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/20476928/", summary:"轮椅上的信仰追问，苦难里开出的澄明之花。", tags:["散文","国产","哲思"], },
  { title:"皮囊", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/37144125/", summary:"故乡亲人与皮囊之下，如何安放肉身与灵魂。", tags:["散文","国产","乡土"], },
  { title:"一个人的村庄", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/1692648/", summary:"新疆村庄的草木虫鸣，慢下来的乡土哲学。", tags:["散文","国产","乡土"], },
  { title:"夜航西飞", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/30187222/", summary:"女飞行员的非洲回忆，自由与孤独的云端独白。", tags:["传记","英国","非洲"], },
  { title:"刀锋", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/35404991/", summary:"拉里寻道之旅，毛姆追问人生何以为值得。", tags:["小说","英国","哲思"], },
  { title:"月亮与六便士", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/26954760/", summary:"抛下一切追梦的画家，理想与现实的永恒撕扯。", tags:["小说","英国","理想"], },
  { title:"人间词话", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/1203426/", summary:"境界说重估词史，中国古典美学的点睛之笔。", tags:["诗词","国产","美学"], },
  { title:"唐宋词十七讲", category:"文学", source:"豆瓣", url:"https://www.douban.com/search?q=%E5%94%90%E5%AE%8B%E8%AF%8D%E5%8D%81%E4%B8%83%E8%AE%B2%20%E5%8F%B6%E5%98%89%E8%8E%B9", summary:"叶嘉莹讲透唐宋词心，带你入词的门径。", tags:["诗词","国产","讲析"], },
  { title:"诗人十四个", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/34463395/", summary:"春山与李杜，用现代心理解读古典诗人的困与美。", tags:["诗词","国产","解读"], },
  { title:"汪曾祺散文", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/1398441/", summary:"一食一味皆成文，最人间烟火的温柔老头。", tags:["散文","国产","生活"], },
  { title:"张爱玲文集", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/1004992/", summary:"红玫瑰与白玫瑰，苍凉手笔写尽男女情爱的算计。", tags:["小说","国产","民国"], },
  { title:"沈从文小说选", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/25931952/", summary:"湘西世界的水手与翠翠，纯美人情风俗画卷。", tags:["小说","国产","乡土"], },
  { title:"鲁迅杂文选", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/26697791/", summary:"投枪与匕首，先生杂文里的清醒与锋芒。", tags:["杂文","国产","思辨"], },
  { title:"木心文学回忆录", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/26451439/", summary:"木心谈文学史，从希腊到唐宋的私人美学讲义。", tags:["文学","国产","讲义"], },
  { title:"红楼梦", category:"文学", source:"豆瓣", url:"https://book.douban.com/subject/1029657/", summary:"字字看来皆是血，一部封建家族的悲金悼玉梦。", tags:["名著","古典","悲剧"], },
  { title:"如何开始写小说", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%A6%82%E4%BD%95%E5%BC%80%E5%A7%8B%E5%86%99%E5%B0%8F%E8%AF%B4", summary:"从一句想写的话起步，新手迈出长篇第一步的实操路径。", tags:["入门","小说","方法"], },
  { title:"小说开头的几种写法", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%B0%8F%E8%AF%B4%E5%BC%80%E5%A4%B4%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"钩子、悬疑、对话，拆解让人放不下的开篇。", tags:["技巧","开篇","结构"], },
  { title:"怎样写出好的人物对话", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E6%80%8E%E4%B9%88%E5%86%99%E4%BA%BA%E7%89%A9%E5%AF%B9%E8%AF%9D", summary:"对话要推剧情而非灌水，让角色自己说话的诀窍。", tags:["对话","人物","技巧"], },
  { title:"新手写作常见的误区", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E6%96%B0%E6%89%8B%E5%86%99%E4%BD%9C%20%E5%B8%B8%E8%A7%81%E8%AF%AF%E5%8C%BA", summary:"堆辞藻、没结构、不敢删，避开最容易踩的坑。", tags:["避坑","入门","反思"], },
  { title:"如何构建世界观", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%B0%8F%E8%AF%B4%20%E4%B8%96%E7%95%8C%E8%A7%82%20%E6%80%8E%E4%B9%88%E6%9E%84%E5%BB%BA", summary:"从规则到细节，为奇幻科幻搭自洽的想象地基。", tags:["世界观","设定","科幻"], },
  { title:"Show don't tell 怎么练", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=show%20don't%20tell%20%E5%86%99%E4%BD%9C", summary:"用画面代替形容，把告诉变成读者自己看见。", tags:["技巧","描写","进阶"], },
  { title:"如何克服写作瓶颈", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%86%99%E4%BD%9C%20%E5%8D%A1%E6%96%87%20%E7%93%B6%E9%A2%88", summary:"卡文不是天赋问题，用方法节奏熬过枯竭期。", tags:["瓶颈","心态","方法"], },
  { title:"怎样写一个有张力的故事", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E6%95%85%E4%BA%8B%20%E5%BC%A0%E5%8A%9B%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"冲突、代价、反转，让故事始终绷着一根弦。", tags:["故事","张力","结构"], },
  { title:"编剧的节奏控制", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E7%BC%96%E5%89%A7%20%E8%8A%82%E5%A5%8F%20%E6%8E%A7%E5%88%B6", summary:"三幕式与节拍表，把两小时讲得松紧有度。", tags:["编剧","节奏","影视"], },
  { title:"如何写好结尾", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%B0%8F%E8%AF%B4%20%E7%BB%93%E5%B0%BE%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"收束不是结束，让结尾余韵绕梁的几种写法。", tags:["结尾","结构","技巧"], },
  { title:"网文大纲怎么写", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E7%BD%91%E6%96%87%20%E5%A4%A7%E7%BA%B2%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"金手指、主线、爽点，长篇小说不写崩的骨架。", tags:["网文","大纲","长篇"], },
  { title:"非虚构写作入门", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E9%9D%9E%E8%99%9A%E6%9E%84%E5%86%99%E4%BD%9C%20%E5%85%A5%E9%97%A8", summary:"真实比虚构更难，特稿与纪实的取材与结构法。", tags:["非虚构","纪实","入门"], },
  { title:"如何写出画面感", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%86%99%E4%BD%9C%20%E7%94%BB%E9%9D%A2%E6%84%9F%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"通感与细节，让读者脑中自动播放电影的写法。", tags:["描写","画面","技巧"], },
  { title:"写作素材怎么积累", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%86%99%E4%BD%9C%E7%B4%A0%E6%9D%90%20%E6%80%8E%E4%B9%88%E7%A7%AF%E7%B4%AF", summary:"素材本、剪报、观察，把生活变成取之不尽的矿。", tags:["素材","习惯","方法"], },
  { title:"如何找到自己的写作风格", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%86%99%E4%BD%9C%E9%A3%8E%E6%A0%BC%20%E6%80%8E%E4%B9%88%E5%BD%A2%E6%88%90", summary:"模仿到形成声音，风格是读写的长年沉淀。", tags:["风格","成长","进阶"], },
  { title:"改稿的七个步骤", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E6%94%B9%E7%A8%BF%20%E6%AD%A5%E9%AA%A4%20%E6%96%B9%E6%B3%95", summary:"初稿靠写二稿靠改，系统打磨让文字脱胎换骨。", tags:["改稿","方法","进阶"], },
  { title:"如何写人物小传", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E4%BA%BA%E7%89%A9%E5%B0%8F%E4%BC%A0%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"前史、欲望、恐惧，立体人物从一张档案表开始。", tags:["人物","设定","技巧"], },
  { title:"悬疑小说怎么设局", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E6%82%AC%E7%96%91%E5%B0%8F%E8%AF%B4%20%E6%80%8E%E4%B9%88%E8%AE%BE%E5%B1%80", summary:"红鲱鱼与伏笔，让读者被骗得心服口服的布局。", tags:["悬疑","结构","技巧"], },
  { title:"散文写作技巧", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E6%95%A3%E6%96%87%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"形散神不散，把日常写出意味的散文心法。", tags:["散文","随笔","技巧"], },
  { title:"如何写对话不尴尬", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%AF%B9%E8%AF%9D%20%E4%B8%8D%E5%B0%B4%E5%B0%AC%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"去掉汇报式台词，让对话像真人在聊天。", tags:["对话","避坑","技巧"], },
  { title:"写作与阅读的关系", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%86%99%E4%BD%9C%20%E9%98%85%E8%AF%BB%20%E5%85%B3%E7%B3%BB", summary:"输入决定输出，怎样读才能反哺自己的笔。", tags:["阅读","方法","习惯"], },
  { title:"如何坚持日更", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%86%99%E4%BD%9C%20%E5%9D%9A%E6%8C%81%E6%97%A5%E6%9B%B4%20%E6%96%B9%E6%B3%95", summary:"把写作变成本能，对抗拖延与完美主义的日更术。", tags:["习惯","坚持","方法"], },
  { title:"金句怎么炼成", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E9%87%91%E5%8F%A5%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"节奏与反差，让一句话被人记住并转发的秘诀。", tags:["金句","技巧","表达"], },
  { title:"故事结构的经典模型", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E6%95%85%E4%BA%8B%E7%BB%93%E6%9E%84%20%E6%A8%A1%E5%9E%8B%20%E8%8B%B1%E9%9B%84%E4%B9%8B%E6%97%85", summary:"英雄之旅到救猫咪，拿来就能用的结构工具箱。", tags:["结构","模型","故事"], },
  { title:"如何写环境描写", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E7%8E%AF%E5%A2%83%E6%8F%8F%E5%86%99%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"景为情设，用环境替角色说话的描写方法。", tags:["环境","描写","技巧"], },
  { title:"投稿与出版常识", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E6%8A%95%E7%A8%BF%20%E5%87%BA%E7%89%88%20%E5%B8%B8%E8%AF%86", summary:"投稿信、版税、合约，新手作者避坑的出版入门。", tags:["出版","投稿","常识"], },
  { title:"自媒体写作逻辑", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E8%87%AA%E5%AA%92%E4%BD%93%20%E5%86%99%E4%BD%9C%20%E9%80%BB%E8%BE%91", summary:"选题、标题、钩子，爆款背后的用户思维。", tags:["自媒体","爆款","方法"], },
  { title:"如何写书评", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E4%B9%A6%E8%AF%84%20%E6%80%8E%E4%B9%88%E5%86%99", summary:"不剧透有观点，写出让人想读原书的好书评。", tags:["书评","方法","表达"], },
  { title:"创意写作练习方法", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%88%9B%E6%84%8F%E5%86%99%E4%BD%9C%20%E7%BB%83%E4%B9%A0%20%E6%96%B9%E6%B3%95", summary:"自由书写与限定写作，每天十分钟激活灵感。", tags:["练习","灵感","方法"], },
  { title:"写作中的留白艺术", category:"写作指导", source:"知乎", url:"https://www.zhihu.com/search?type=content&q=%E5%86%99%E4%BD%9C%20%E7%95%99%E7%99%BD%20%E8%89%BA%E6%9C%AF", summary:"不说尽比说尽更高级，留白让文字有了呼吸。", tags:["技巧","进阶","审美"], },
  { title:"故事FM", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E6%95%85%E4%BA%8BFM", summary:"每个人的声音都值得被听见，普通人的真实故事集。", tags:["故事","纪实","访谈"], type:"podcast", },
  { title:"跳岛FM", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E8%B7%B3%E5%B2%9BFM", summary:"文学播客里的清流，作家编辑聊书与阅读现场。", tags:["文学","读书","访谈"], type:"podcast", },
  { title:"知行小酒馆", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E7%9F%A5%E8%A1%8C%E5%B0%8F%E9%85%92%E9%A6%86", summary:"聊聊金钱与自我成长，把理财讲成生活哲学。", tags:["投资","成长","理财"], type:"podcast", },
  { title:"不合时宜", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E4%B8%8D%E5%90%88%E6%97%B6%E5%AE%9C", summary:"三个媒体人的世界观察，在变动时代保持清醒。", tags:["时事","文化","对话"], type:"podcast", },
  { title:"忽左忽右", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E5%BF%BD%E5%B7%A6%E5%BF%BD%E5%8F%B3", summary:"程衍樑聊历史与当下，知识密度极高的对谈。", tags:["历史","文化","对谈"], type:"podcast", },
  { title:"随机波动", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E9%9A%8F%E6%9C%BA%E6%B3%A2%E5%8A%A8", summary:"三位女性创作者，从日常聊到性别与创作。", tags:["女性","文化","对话"], type:"podcast", },
  { title:"文化有限", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E6%96%87%E5%8C%96%E6%9C%89%E9%99%90", summary:"三个普通读者的读书会，轻松好读的聊书现场。", tags:["读书","闲聊","推荐"], type:"podcast", },
  { title:"声东击西", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E5%A3%B0%E4%B8%9C%E5%87%BB%E8%A5%BF", summary:"科技与商业的边界观察，全球视野的硬核对谈。", tags:["科技","商业","全球"], type:"podcast", },
  { title:"杯弓舌瘾", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E6%9D%AF%E5%BC%93%E8%88%8C%E7%98%BE", summary:"从一杯酒聊到饮食文化，舌尖上的知识与故事。", tags:["美食","文化","闲聊"], type:"podcast", },
  { title:"艺术有得聊", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E8%89%BA%E6%9C%AF%E6%9C%89%E5%BE%97%E8%81%8A", summary:"用大白话讲艺术史，把高冷名画聊进生活。", tags:["艺术","科普","闲聊"], type:"podcast", },
  { title:"天才女友", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E5%A4%A9%E6%89%8D%E5%A5%B3%E5%8F%8B", summary:"女性创作者的灵感现场，写作与生活的诚实对话。", tags:["女性","创作","文学"], type:"podcast", },
  { title:"展开讲讲", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E5%B1%95%E5%BC%80%E8%AE%B2%E8%AE%B2", summary:"从影视热点聊到社会情绪，年轻人的文化夜谈。", tags:["影视","文化","闲聊"], type:"podcast", },
  { title:"看理想电台", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E7%9C%8B%E7%90%86%E6%83%B3%E7%94%B5%E5%8F%B0", summary:"梁文道们的文化客厅，把知识与思想慢慢讲。", tags:["文化","思想","访谈"], type:"podcast", },
  { title:"八分", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E5%85%AB%E5%88%86%20%E6%A2%81%E6%96%87%E9%81%93", summary:"梁文道评说时事与文化，清醒克制的一家之言。", tags:["时事","文化","评论"], type:"podcast", },
  { title:"螺丝在拧紧", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E8%9E%BA%E4%B8%9D%E5%9C%A8%E6%8B%A7%E7%B4%A7", summary:"影视与文化的深度对谈，专业又不端着。", tags:["影视","文化","对谈"], type:"podcast", },
  { title:"基本无害", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E5%9F%BA%E6%9C%AC%E6%97%A0%E5%AE%B3%20%E6%92%AD%E5%AE%A2", summary:"科幻迷的硬核闲聊，从小说聊到科学与未来。", tags:["科幻","闲聊","文化"], type:"podcast", },
  { title:"晚风说", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E6%99%9A%E9%A3%8E%E8%AF%B4", summary:"创业者与艺术家的深夜对谈，真诚得有点刺痛。", tags:["访谈","创业","人生"], type:"podcast", },
  { title:"无人知晓", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E6%97%A0%E4%BA%BA%E7%9F%A5%E6%99%93%20%E5%AD%9F%E5%B2%A9", summary:"孟岩聊投资与人生，把复利讲成长期主义。", tags:["投资","人生","理财"], type:"podcast", },
  { title:"组织进化论", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E7%BB%84%E7%BB%87%E8%BF%9B%E5%8C%96%E8%AE%BA", summary:"聊聊公司与人的协作，组织如何更好地生长。", tags:["职场","管理","成长"], type:"podcast", },
  { title:"三好坏男孩", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E4%B8%89%E5%A5%BD%E5%9D%8F%E7%94%B7%E5%AD%A9", summary:"三个男生的真诚闲聊，把生活琐事聊出笑与思。", tags:["闲聊","生活","幽默"], type:"podcast", },
  { title:"水星记", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E6%B0%B4%E6%98%9F%E8%AE%B0%20%E6%92%AD%E5%AE%A2", summary:"聊音乐与情绪，用声音记录星河般的日常。", tags:["音乐","情绪","闲聊"], type:"podcast", },
  { title:"去现场", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E5%8E%BB%E7%8E%B0%E5%9C%BA%20%E6%92%AD%E5%AE%A2", summary:"走进事件发生的现场，用声音还原真实质感。", tags:["纪实","现场","访谈"], type:"podcast", },
  { title:"灭鼠行动", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E7%81%AD%E9%BC%A0%E8%A1%8C%E5%8A%A8", summary:"幽默又犀利的文化闲聊，把冷知识聊成热话题。", tags:["文化","幽默","闲聊"], type:"podcast", },
  { title:"不在场", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E4%B8%8D%E5%9C%A8%E5%9C%BA%20%E6%92%AD%E5%AE%A2", summary:"关于电影与存在的对谈，在光影里寻找意义。", tags:["电影","文化","对谈"], type:"podcast", },
  { title:"海豹电台", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E6%B5%B7%E8%B1%B9%E7%94%B5%E5%8F%B0", summary:"温柔治愈的睡前絮语，给疲惫的人一点抱抱。", tags:["治愈","闲聊","陪伴"], type:"podcast", },
  { title:"视知", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E8%A7%86%E7%9F%A5%20%E6%92%AD%E5%AE%A2", summary:"把硬知识讲成好故事，科普与常识的声音版。", tags:["科普","知识","闲聊"], type:"podcast", },
  { title:"时间之间", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E6%97%B6%E9%97%B4%E4%B9%8B%E9%97%B4%20%E6%92%AD%E5%AE%A2", summary:"聊聊时间与记忆，在流逝里打捞生活的意义。", tags:["文化","哲思","对谈"], type:"podcast", },
  { title:"从零到英雄", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E4%BB%8E%E9%9B%B6%E5%88%B0%E8%8B%B1%E9%9B%84", summary:"创业者的真实路径，从零到一的血与汗。", tags:["创业","访谈","成长"], type:"podcast", },
  { title:"不可理论", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E4%B8%8D%E5%8F%AF%E7%90%86%E8%AE%BA", summary:"用理论照亮生活，把学术概念聊得接地气。", tags:["学术","文化","对谈"], type:"podcast", },
  { title:"新闻酸菜馆", category:"播客", source:"Apple播客", url:"https://podcasts.apple.com/cn/search?term=%E6%96%B0%E9%97%BB%E9%85%B8%E8%8F%9C%E9%A6%86", summary:"用轻松口吻聊严肃新闻，信息量与趣味兼得。", tags:["新闻","时事","闲聊"], type:"podcast", },
  { title:"静夜思", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E9%9D%99%E5%A4%9C%E6%80%9D", summary:"床前明月光，千古游子思乡的第一声叹息。", tags:["唐诗","李白","思乡"], },
  { title:"春江花月夜", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E6%98%A5%E6%B1%9F%E8%8A%B1%E6%9C%88%E5%A4%9C", summary:"孤篇压全唐，江月千里写尽哲思与离愁。", tags:["唐诗","张若虚","哲思"], },
  { title:"将进酒", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E5%B0%86%E8%BF%9B%E9%85%92", summary:"天生我材必有用，李白豪饮中的狂放与悲慨。", tags:["唐诗","李白","豪放"], },
  { title:"登高", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E7%99%BB%E9%AB%98%20%E6%9D%9C%E7%94%AB", summary:"无边落木萧下，杜甫潦倒中的沉雄与苍凉。", tags:["唐诗","杜甫","悲秋"], },
  { title:"锦瑟", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E9%94%A6%E7%91%9F%20%E6%9D%8E%E5%95%86%E9%9A%90", summary:"此情可待成追忆，朦胧诗里最缠绵的怅惘。", tags:["唐诗","李商隐","爱情"], },
  { title:"声声慢", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E5%A3%B0%E5%A3%B0%E6%85%A2%20%E6%9D%8E%E6%B8%85%E7%85%A7", summary:"寻寻觅觅冷冷清清，易安晚景的凄凄惨惨。", tags:["宋词","李清照","婉约"], },
  { title:"雨霖铃", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E9%9B%A8%E9%9C%96%E9%93%83%20%E6%9F%B3%E6%B0%B8", summary:"杨柳岸晓风残月，柳七的离情别绪动人千年。", tags:["宋词","柳永","离别"], },
  { title:"念奴娇·赤壁怀古", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E5%BF%B5%E5%A5%B4%E5%A8%87%20%E8%B5%A4%E5%A3%81%E6%80%80%E5%8F%A4", summary:"大江东去浪淘尽，东坡的豪情与旷达。", tags:["宋词","苏轼","怀古"], },
  { title:"水调歌头·明月几时有", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E6%B0%B4%E8%B0%83%E6%AD%8C%E5%A4%B4%20%E6%98%8E%E6%9C%88%E5%87%A0%E6%97%B6%E6%9C%89", summary:"但愿人长久千里共婵娟，中秋最深情的一问。", tags:["宋词","苏轼","中秋"], },
  { title:"沁园春·雪", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E6%B2%81%E5%9B%AD%E6%98%A5%20%E9%9B%AA", summary:"江山如此多娇，一代伟人的宏大胸襟与气魄。", tags:["现代","词","豪放"], },
  { title:"天净沙·秋思", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E5%A4%A9%E5%87%80%E6%B2%99%20%E7%A7%8B%E6%80%9D", summary:"断肠人在天涯，二十八字写尽羁旅苍茫。", tags:["元曲","马致远","羁旅"], },
  { title:"虞美人·春花秋月", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E8%99%9E%E7%BE%8E%E4%BA%BA%20%E6%98%A5%E8%8A%B1%E7%A7%8B%E6%9C%88", summary:"问君能有几多愁，亡国之君的血泪绝唱。", tags:["词","李煜","亡国"], },
  { title:"如梦令·常记溪亭", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E5%A6%82%E6%A2%A6%E4%BB%A4%20%E6%9D%8E%E6%B8%85%E7%85%A7", summary:"争渡惊起一滩鸥鹭，少女李清照的烂漫时光。", tags:["宋词","李清照","闲趣"], },
  { title:"饮酒·其五", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E9%A5%AE%E9%85%92%20%E5%85%B6%E4%BA%94%20%E9%99%B6%E6%B8%8A%E6%98%8E", summary:"采菊东篱下悠然见南山，归隐者的恬淡自得。", tags:["古诗","陶渊明","隐逸"], },
  { title:"归园田居", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E5%BD%92%E5%9B%AD%E7%94%B0%E5%B1%85%20%E9%99%B6%E6%B8%8A%E6%98%8E", summary:"久在樊笼里复得返自然，田园诗的源头活水。", tags:["古诗","陶渊明","田园"], },
  { title:"陋室铭", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E9%99%8B%E5%AE%A4%E9%93%AD", summary:"斯是陋室惟吾德馨，安贫乐道的君子之风。", tags:["古文","刘禹锡","励志"], },
  { title:"爱莲说", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E7%88%B1%E8%8E%B2%E8%AF%B4", summary:"出淤泥而不染，一篇短文立起君子精神坐标。", tags:["古文","周敦颐","品格"], },
  { title:"岳阳楼记", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E5%B2%B3%E9%98%B3%E6%A5%BC%E8%AE%B0", summary:"先天下之忧而忧，一篇记文写尽士人胸怀。", tags:["古文","范仲淹","胸怀"], },
  { title:"醉翁亭记", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E9%86%89%E7%BF%81%E4%BA%AD%E8%AE%B0", summary:"醉翁之意不在酒，与民同乐的从容与风流。", tags:["古文","欧阳修","闲适"], },
  { title:"赤壁赋", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E8%B5%A4%E5%A3%81%E8%B5%8B%20%E8%8B%8F%E8%BD%BC", summary:"哀吾生之须臾慕长江之无穷，东坡的旷达之夜。", tags:["古文","苏轼","哲思"], },
  { title:"滕王阁序", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E6%BB%95%E7%8E%8B%E9%98%81%E5%BA%8F", summary:"落霞与孤鹜齐飞，少年王勃的惊才绝艳。", tags:["古文","王勃","骈文"], },
  { title:"蜀道难", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E8%9C%80%E9%81%93%E9%9A%BE", summary:"蜀道之难难于上青天，太白的浪漫与险峻。", tags:["唐诗","李白","浪漫"], },
  { title:"茅屋为秋风所破歌", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E8%8C%85%E5%B1%8B%E4%B8%BA%E7%A7%8B%E9%A3%8E%E6%89%80%E7%A0%B4%E6%AD%8C", summary:"安得广厦千万间，寒士杜甫的大庇天下心。", tags:["唐诗","杜甫","忧民"], },
  { title:"琵琶行", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E7%90%B5%E7%90%B6%E8%A1%8C%20%E7%99%BD%E5%B1%85%E6%98%93", summary:"同是天涯沦落人，江州司马的青衫泪。", tags:["唐诗","白居易","沦落"], },
  { title:"长恨歌", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E9%95%BF%E6%81%A8%E6%AD%8C%20%E7%99%BD%E5%B1%85%E6%98%93", summary:"天长地久有时尽此恨绵绵无绝期，帝妃悲歌。", tags:["唐诗","白居易","爱情"], },
  { title:"蒹葭", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E8%92%B9%E8%91%AD%20%E8%AF%97%E7%BB%8F", summary:"所谓伊人在水一方，诗经里最缥缈的追寻。", tags:["诗经","爱情","朦胧"], },
  { title:"关雎", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E5%85%B3%E9%9B%8E%20%E8%AF%97%E7%BB%8F", summary:"窈窕淑女君子好逑，国人爱情诗篇的源头。", tags:["诗经","爱情","经典"], },
  { title:"沁园春·长沙", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E6%B2%81%E5%9B%AD%E6%98%A5%20%E9%95%BF%E6%B2%99", summary:"问苍茫大地谁主沉浮，青年毛泽东的壮怀。", tags:["现代","词","壮志"], },
  { title:"定风波·莫听穿林", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E5%AE%9A%E9%A3%8E%E6%B3%A2%20%E8%8B%8F%E8%BD%BC", summary:"一蓑烟雨任平生，东坡的从容与豁达。", tags:["宋词","苏轼","豁达"], },
  { title:"登鹳雀楼", category:"诗词文学", source:"古诗文网", url:"https://so.gushiwen.cn/search.aspx?value=%E7%99%BB%E9%B9%B3%E9%9B%80%E6%A5%BC", summary:"欲穷千里目更上一层楼，盛唐的昂扬与进取。", tags:["唐诗","王之涣","励志"], }
];
